### ISSUE TITLE
Demo: Selecting the select sources window itself cause weird issues

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/ashpd#17]
When you select a window in `select sources window`, and pick the `select sources window` itself from the selection. It sometimes crash, and when it doesn't, it will make the parts of the demo, where the window identifier needs to be exported unusable, unless you restart the demo.

https://user-images.githubusercontent.com/64297935/128160515-b7bcd261-be5e-485a-944d-cea6477f543b.mp4

**Comment by bilelmoussaoui** [comment]
The crash shouldn't happen, it's probably from the portal side. The identifier issue is a known issue (e.g, try the inhibit page). That's because we unexport the handle once the identifier is dropped and it doesn't seems to be the case here for whatever reasons (could be some async function still waiting to be executed or whatever)

**Comment by SeaDve** [comment]
It doesn't really crash/panic. It just starts to not respond on those certain times

**Comment by bilelmoussaoui** [comment]
What I meant is the portal shouldn't even allow you to select such window

**Comment by bilelmoussaoui** [comment]
I believe we can't do anything from ashpd/the demo itself. Please report that to xdg-desktop-portal itself.

Thanks
